### ISSUE TITLE
SCSS auto-indent not matching code mirror functionality.

### ISSUE THREAD

**Issue by zackmvmt** [lambdahands/lt-scss#4]
First, thanks for making such an awesome plugin. This has worked out great except for one minor annoyance with the auto-indent functionality not matching code mirror.

When I place my cursor at the closing `}` of the `.foo a` style and hit enter, the next line is not indented correctly. It should be two indents in and it's currently zero indents in.

``` scss
body {
    background-color: white;
    font-family: serif;
    .foo {
        background-color: lime;
        text-decoration: none;
        a {
            color: red;
        }
    }
}
```

Interestingly enough, when I try the same action with the same code on the code mirror site, it is handled correctly. http://codemirror.net/mode/css/scss.html

Am I doing something wrong, or is this a legitimate issue? It seems like there were a couple of issues with the code mirror indenting that got fixed a few months ago. Perhaps those fixes didn't make it to this plugin?
